using Test
include("unit/solver_tests.jl")
include("unit/analytic_small_graph.jl")
include("unit/regularization_tests.jl")
include("unit/pairs_io_tests.jl")
include("unit/selfloop_tests.jl")
include("unit/negative_weights_tests.jl")
include("unit/metrics_prediction_tests.jl")
include("unit/metrics_correlation_tests.jl")
include("unit/metrics_proba_tests.jl")
include("unit/graphs_api_tests.jl")
include("unit/krylov_plpr_passthrough.jl")
include("unit/solver_variants_tests.jl")
